package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.AbstractC6700h;
import com.google.android.gms.common.api.AbstractC6836p;
import com.google.android.gms.common.api.AbstractC6837q;
import com.google.android.gms.common.api.InterfaceC6833m;
import com.google.android.gms.common.api.InterfaceC6834n;
import com.google.android.gms.common.api.Status;
import java.util.concurrent.TimeUnit;

/* JADX INFO: renamed from: com.google.android.gms.common.api.internal.L0 */
/* JADX INFO: loaded from: classes2.dex */
public final class C6726L0<R extends InterfaceC6833m> extends AbstractC6700h<R> {

    /* JADX INFO: renamed from: a */
    private final Status f29879a;

    /* JADX INFO: renamed from: a */
    final Status m29409a() {
        return this.f29879a;
    }

    @Override // com.google.android.gms.common.api.AbstractC6700h
    public final void addStatusListener(AbstractC6700h.a aVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC6700h
    public final R await() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC6700h
    public final void cancel() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC6700h
    public final boolean isCanceled() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC6700h
    public final void setResultCallback(InterfaceC6834n<? super R> interfaceC6834n) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC6700h
    public final <S extends InterfaceC6833m> AbstractC6837q<S> then(AbstractC6836p<? super R, ? extends S> abstractC6836p) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC6700h
    public final R await(long j10, TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC6700h
    public final void setResultCallback(InterfaceC6834n<? super R> interfaceC6834n, long j10, TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
